language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - gh-pages

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $99ae03980d283a40263f641b918b92c034cb6b98
  target-branch: master
  local-dir: dist
  on:
    branch: gh-pages